// shell/src/frame_systems.rs
//
// This module pulls in the Rust code generated by framec from the .frs files
// in the workspace's frame/ directory. The generated files live in OUT_DIR
// (per Cargo convention for build-script outputs); we include them here so
// the rest of the crate can refer to the Frame systems by name.
//
// One include! per Frame system. Order matters only if a system references
// another system as a domain field — for H0 there's just one, so no ordering
// concern yet.
//
// To regenerate: edit the .frs files in the workspace's frame/ directory,
// then `cargo build`. The build script will re-run framec on each.
//
// The `use` lines below import items that the Frame-generated code
// references from inside its wrapping `mod _<name>_framec { use super::*; }`
// — `super::*` glob-imports whatever is visible here. Adding a domain
// field referencing a type from another module of this crate? Import it
// here so the generated module can see it.

use crate::builtin::{classify, execute, Builtin};

include!(concat!(env!("OUT_DIR"), "/shell.rs"));
include!(concat!(env!("OUT_DIR"), "/parser.rs"));
